# Generated by Django 5.1.3 on 2024-12-03 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_produto_movimentacaoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='equipment.operacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.produto')),
            ],
        ),
    ]
