# Generated by Django 5.1.3 on 2024-12-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_estoqueoperacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='codigo',
        ),
    ]
