# Generated by Django 5.1.3 on 2024-12-04 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_modelo_alter_equipamento_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='codigo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='operacao',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='nome',
        ),
        migrations.AddField(
            model_name='operacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='operacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.produto'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operacao',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='entrada', max_length=10),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='descricao',
            field=models.CharField(help_text='Descrição da manutenção', max_length=255),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='horimetro_realizacao',
            field=models.PositiveIntegerField(blank=True, help_text='Horímetro na realização da manutenção', null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='intervalo_horas',
            field=models.PositiveIntegerField(help_text='Intervalo de horas para manutenção'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='operacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='equipment.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=50),
        ),
        migrations.DeleteModel(
            name='EstoqueOperacao',
        ),
    ]
