# Generated by Django 5.1.3 on 2024-12-06 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_rename_codigo_produto_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='operacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.operacao'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='nome',
            field=models.CharField(default='-----', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='horimetro_realizacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='intervalo_horas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='operacao',
            field=models.ForeignKey(help_text='Operação associada à movimentação', on_delete=django.db.models.deletion.CASCADE, to='equipment.operacao'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10),
        ),
        migrations.CreateModel(
            name='EstoqueOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='equipment.operacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.produto')),
            ],
        ),
    ]
