# Generated by Django 5.1.3 on 2024-12-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_remove_movimentacaoestoque_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.operacao'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='descricao',
            field=models.CharField(help_text='Descrição da manutenção', max_length=255),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='horimetro_realizacao',
            field=models.PositiveIntegerField(blank=True, help_text='Horímetro na realização da manutenção', null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='intervalo_horas',
            field=models.PositiveIntegerField(help_text='Intervalo de horas para manutenção'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='equipment.modelo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='equipment.produto'),
        ),
    ]
