# Generated by Django 5.1.3 on 2024-12-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_movimentacaoestoque_operacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='equipamentos',
        ),
    ]
