# Generated by Django 5.1.4 on 2025-01-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_remove_produto_equipamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueoperacao',
            name='locacao',
            field=models.CharField(blank=True, help_text='Código de locação ou referência', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estoqueoperacao',
            name='prateleira',
            field=models.CharField(blank=True, help_text='Localização no estoque', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observação sobre a movimentação', null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='prateleira',
            field=models.CharField(blank=True, help_text='Localização no estoque', max_length=100, null=True),
        ),
    ]
