# Generated by Django 5.1.4 on 2025-01-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_estoqueoperacao_locacao_estoqueoperacao_prateleira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='locacao',
            field=models.CharField(blank=True, help_text='Código de locação ou referência', max_length=100, null=True),
        ),
    ]
