# Generated by Django 5.1.4 on 2025-01-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_movimentacaoestoque_locacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='codigo',
        ),
    ]
