# Generated by Django 5.1.4 on 2025-01-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_rename_nome_produto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='obra_atual',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='operacao',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='equipamento',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Obra',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='Manutencao',
        ),
    ]
